# -*- coding: utf-8 -*-
"""Trabajo programacion Jose Samuel Turpo Cauna.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PQwJmxdfdLSu2TqDxSv1s3b5E_GCnPko

2.1 Realice un diagrama de flujo y pseudocódigo que representen el algoritmo para obtener el área de un triángulo.
"""

#Definir variable
base:float
altura:float
area:float
#Datos de entrada
base=float(input("Ingrese la base: "))
altura=float(input("Ingrese la altura: "))
#Proceso
area=base*altura/2
#Datos de salida
print(f"El area es: {area}")

"""2.2 Una empresa importadora desea determinar cuántos dólares puede adquirir con equis cantidad de dinero en soles realice un diagrama de flujo y pseudocódigo que represente un algoritmo para tal fin. """

#Definir variables
soles:float
dolares:float
#Datos de entrada
soles=float(input("Ingrese la cantidad de soles: "))
#Proceso
dolares=soles/3.77
#Datos de salida
print(f"La cantidad dolares son: {dolares}")

"""2.3 Una empresa que contrata personal requiere determinar la edad de las personas que solicitan trabajo, pero cuando se les realiza la entrevista sólo se les pregunta el año en que nacieron.  Realice el diagrama de flujo y pseudocódigo que represente el algoritmo para solucionar este problema."""

#Definir variables
añoactual:float
añonacer:float
edad:float
#Datos de entrada
añoactual=float(input("Ingrese el año actual: "))
añonacer=float(input("Ingrese el año de nacimiento: "))
#Proceso
edad=añoactual-añonacer
#Datos de salida
print(f"Tiene {edad} años")

"""2.4 Un estacionamiento requiere determinar el cobro que debe aplicar a las personas que lo utilizan. Considere que el cobro es con base en las horas que lo disponen y que las fracciones de hora se toman como completas y realice un diagrama de flujo y pseudocódigo que represente el algoritmo que permita determinar el cobro."""

#Definir variables
PxH:float
HU:float
Total:float
#Datos de entrada
PxH=float(input("Ingrese el cobro por hora: "))
HU=float(input("Ingrese las horas estacionado: "))
#Proceso
Total=PxH*HU
#Datos de salida
print(f"El cobro total es: {Total}")

"""2.5 Constructoras Juliaca requiere determinar cuánto cobrar por trabajos de pintura. Considere que se cobra por m2 y realice un diagrama de flujo y pseudocódigo que represente el algoritmo que le permita ir generando presupuestos para cada cliente."""

#Definir variables
altura:float
ancho:float
m2:float
cobro:float
cantidad:float
total:float
#Datos de entrada
altura=float(input("Ingrese la altura: "))
ancho=float(input("Ingrese los ancho: "))
cobro=float(input("Ingrese el cobro por m²: "))
cantidad=float(input("Ingrese la cantidad de pinturas: "))
#Proceso
m2=altura*ancho
total=m2*cobro*cantidad
#Datos de salida
print(f"El cobro total es: {total}")

"""2.6 Se requiere determinar la hipotenusa de un triángulo rectángulo ¿cómo sería el diagrama de flujo y el pseudocódigo que represente el algoritmo para obtenerla? Recuerde que por Pitágoras c^ {2} =a^ {2} +b^ {2}"""

#Definir variables
C1:float
C2:float
H:float
#Datos de entrada
C1=float(input("Ingrese el cateto adyacente: "))
C2=float(input("Ingrese el cateto opuesto: "))
#Proceso
H=(C1**2+C2**2)**0.5
#Datos de salida
print(f"La hipotenusa es: {H}")

"""2.7 Una compañía de autobuses requiere determinar el costo que tendrá el boleto de un viaje, esto basado en los kilómetros por recorrer y el costo es por kilómetro. Realice un diagrama de flujo y pseudocódigo que representen el algoritmo para tal fin."""

#Definir variables
CK:float
KR:float
total:float
#Datos de entrada
CK=float(input("Ingrese el costo por Km: "))
KR=float(input("Ingrese la disancia en Km: "))
#Proceso
total=CK*KR
#Datos de salida
print(f"El costo del boleto es : {total}")

"""2.8 Se requiere determinar el tiempo que tarda una persona en llegar de una ciudad a otra en bicicleta, considerando que lleva una velocidad constante. Realice un diagrama de flujo y pseudocódigo que represente el algoritmo para tal fin. """

#Definir variables
distancia:float
velocidad:float
tiempo:float
#Datos de entrada
distancia=float(input("Escriba la distancia en km: "))
velocidad=float(input("Escriba la velocidad en km: "))
#Proceso
tiempo=distancia/velocidad
#Datos de salida     
print(f"Llegara en: {tiempo} horas")

"""2.9 Se requiere determinar el costo que tendrá, el realizar una llamada telefónica con base en el tiempo que dura la llamada y el costo es por minuto. realice un diagrama de flujo y pseudocódigo que representen el algoritmo para tal fin."""

#Definir variables
TLL:float
CM:float
TOTAL:float
#Datos de entrada
TLL=float(input("Ingrese el tiempo de llamada en minutos: "))
CM=float(input("Ingrese el costo de la llamada: "))
#Proceso
TOTAL=TLL*CM
#Datos de salida
print(f"El costo total es: {TOTAL}")

"""2.10 Seda Juliaca requiere determinar el pago que debe realizar una persona por el total de metros cúbicos de consumo de agua. Realice un diagrama de flujo y pseudocódigo que represente el algoritmo que permita determinar ese pago. """

#Definir variables
litros:float
pl:float
m3:float
total:float
#Datos de entrada
litros=float(input("Ingrese la cantidad de litros: "))
pl=float(input("Ingrese el pago por m^3: "))
#Proceso
m3=litros/1000
total=pl*m3
#Datos de salida
print(f"El pago total es:{total}")

"""2.11 Electro Puno requiere determinar el pago que debe realizar una persona por el consumo de energía eléctrica, la cual se mide en kilowatts(KW).  Realice un diagrama de flujo y pseudocódigo que represente el algoritmo que permita determinar ese pago. """

#Definir variables
KW:float
PKW:float
TOTAL:float
#Datos de entrada
KW=float(input("Ingrese los kilowatts consumidos: "))
PWK=float(input("Ingrese el pago por kilowatts: "))
#Proceso
TOTAL=KW*PWK
#Datos de salida
print(f"El total a pagar es: {TOTAL}")

"""2.12 Realice un diagrama de flujo y pseudocódigo que representen el algoritmo para determinar Cuánto debe pagar finalmente una persona por un artículo equis, Considerando qué tiene un descuento de 20%, y debe pagar 18% de IGV (debe Mostrar el precio con descuento y el precio final)"""

#Definir variables
descuento:float=0.20
igv:float
pbase:float
pcd:float
pf:float
#Datos de entrada
pbase=float(input("ingrese el precio base del articulo: "))
#Proceso
pcd=pbase-(pbase*descuento)
igv=pcd*0.18
print(pcd)
pf=pcd+igv
#Datos de salida
print(f"El precio con descuento es: {pcd}")
print(f"El precio final es: {pf}")

"""2.13 Realice un diagrama de flujo y pseudocódigo que represente el algoritmo para determinar cuánto dinero ahorra una persona en un año, si considera que cada semana ahorra 15% de su sueldo (considere cuatro semanas por mes y que no cambia el sueldo). """

#Definir variables
SPS:float
Total:float
#Datos de entrada
SPS=float(input("Ingrese el sueldo por semana: "))
#Proceso
Total=(SPS*4)*12*0.15
#Datos de salida
print(f"Ahorra por año : {Total} soles")

"""2.14 Una empresa desea determinar el monto de un cheque que debe proporcionar a uno de sus empleados que tendrá que ir por equis número de días a la ciudad de Lima; los gastos que cubre la empresa son:  Hotel, comida y 100 soles diarios para otros gastos.  el monto debe estar desglosado para cada concepto realice un diagrama de flujo y pseudocódigo que represente el algoritmo para determinar el monto del cheque."""

#Definir variables
dias:float
gh:float
gc:float
total:float
H:float
C:float
O:float
#Datos de entrada
dias=float(input("Ingrese los dias de viaje: "))
gc=float(input("Ingrese el gasto por comida diarios: "))
gh=float(input("Ingrese el gasto del hotel diarios: "))
#Proceso
H=gh*dias
C=gc*dias
O=100*dias
total=H+C+O
#Datos de salida
print(f"El total de gasto por comida diarios es: {C}")
print(f"El total de gasto por hospedaje diario es: {H}")
print(f"El total de otros gastos es: {O}")
print(f"El total del gasto del viaje es: {total}")

"""2.15 Se desea calcular la potencia eléctrica de un circuito de la figura 2.6 realice un diagrama de flujo y el pseudocódigo que representen el algoritmo para resolver el problema. Considere que: P=V*I y V=R*L"""

#Definir variables
intensidad:float
resistencia:float=4
potencia:float
#Datos de entrada
intensidad=float(input("Ingrese la intencidad: "))
#Proceso
potencia=resistencia*intensidad*intensidad
#Datos de salida
print(f"La potencia es: {potencia}")

"""2.16 Realice el diagrama de flujo y pseudocódigo que representen el algoritmo para determinar el promedio que obtendrá un alumno considerando que realiza tres exámenes, de los cuales el primero y el segundo tienen una ponderación de 25%, Mientras que el tercero es de 50%."""

#Definir variables
EX1:float
EX2:float
EX3:float
TOTAL:float
#Datos de entrada
EX1=float(input("Ingrese la nota del 1° examen: "))
EX2=float(input("Ingrese la nota del 2° examen: "))
EX3=float(input("Ingrese la nota del 3° examen: "))
#Proceso
TOTAL=(EX1*0.25)+(EX2*0.25)+(EX3*0.5)
#Datos de salida
print(f"El promedio final es: {TOTAL}")

"""2.17 Realice un diagrama de flujo y pseudocódigo que represente el algoritmo para determinar aproximadamente cuántos meses semanas días y horas ha vivido una persona."""

#Definir variables
años:float
meses:float
semanas:float
dias:float
horas:float
#Datos de entrada
años=float(input("Ingrese la edad actual: "))
#Proceso
meses=años*12
semanas=meses*4.34524
dias=semanas*7
horas=dias*24
#Datos de salida
print(f"Los meses vividos es: {meses}")
print(f"Las semanas vividos es: {semanas}")
print(f"Los dias vividos es: {dias}")
print(f"Las horas vividos es: {horas}")

"""2.18 El hotel Maison requiere determinar lo que le debe cobrar a un huésped por su estancia en una de sus habitaciones. Realice un diagrama de flujo y pseudocódigo que represente el algoritmo para determinar ese cobro."""

#Definir variables
dias:float
pxd:float
total:float
#Datos de entrada
dias=float(input("Ingrese la cantidad de dias: "))
pxd=float(input("Ingrese el pago por dias: "))
#Proceso
total=dias*pxd
#Datos de salida
print(f"El pago total es: {total}")

"""2.19 Calcule la longitud de una circunferencia de radio conocido."""

#Definir variables
radio:float
total:float
#Datos de entrada
radio=float(input("Ingrese el radio: "))
#Proceso
total=radio*3.1416*2
#Datos de salida
print(f"La circunferencia es: {total}")

"""2.20 Calcule el área de un trapecio cuyas base menor, base mayor y altura son conocidos"""

#Definir variables
bm:float
bma:float
altura:float
total:float
#Datos de entrada
bm=float(input("Ingrese la base menor: "))
bma=float(input("Ingrese la base mayor: "))
altura=float(input("Ingrese la altura: "))
#Proceso
total=((bma+bm)/2)*altura
#Datos de salida
print(f"El area es: {total}")

"""2.21 Sabiendo que una milla equivale a 1609 Kilómetros, lea una cantidad en millas y conviértala a kilómetros."""

#Definir variables
millas:float
total:float
#Datos de entrada
millas=float(input("Ingrese los millas: "))
#Proceso
total=millas*1609
#Datos de salida
print(f"El total de kilometros es: {total} km")

"""2.22 ¿Cuál es el volumen de un paralelepípedo de largo, ancho y altura conocidas?"""

#Definir variables
largo:float
ancho:float
altura:float
total:float
#Datos de entrada
largo=float(input("Ingrese el largo: "))
ancho=float(input("Ingrese el ancho: "))
altura=float(input("Ingrese la altura: "))
#Proceso
total=largo*ancho*altura
#Datos de salida
print(f"El volumen es: {total}")

"""2.23 Calcule la suma de los n primeros números pares"""

#Definir variables
n:float
n2:float
total:float
#Datos de entrada
n=float(input("Ingrese la cantidad de terminos: "))
#Proceso
total=(n+1)*n
#Datos de salida
print(f"La suma es: {total}")

"""2.24 Lea una hora y diga a cuántas horas, minutos y segundos equivale."""

#Definir variables
hora:float
minutos:float
segundos:float
#Datos de entrada
hora=float(input("Ingrese la cantidad de horas: "))
#Proceso
minutos=hora*60
segundos=minutos*60
#Datos de salida
print(f"Las horas son: {hora}")
print(f"Los minutos son: {minutos}")
print(f"Los segundos son: {segundos}")